nginx:
    image: nginx:latest
    ports:
        - '80:80'
    volumes:
        - ./nginx:/etc/nginx/conf.d
        - ./logs/nginx:/var/log/nginx
        - ./wordpress:/var/www/html
    links:
        - wordpress
    restart: always

wordpress:
    image: wordpress:4.7.1-php7.0-fpm
    ports:
        - '9000:9000'
    volumes:
        - ./wordpress:/var/www/html
    environment:
        - WORDPRESS_DB_USER=REPLACE_DB_USER
        - WORDPRESS_DB_NAME=REPLACE_DB_NAME
        - WORDPRESS_DB_HOST=REPLACE_DB_HOST
        - WORDPRESS_DB_PASSWORD=REPLACE_DB_PASSWORD
        - WORDPRESS_TABLE_PREFIX=wp_
    restart: always

